/** One-time seed from the household's voorraad.xlsx "Voorraad" sheet. */
export interface FoodInventorySeed {
	category: string;
	item: string;
	quantity: number;
	lowStock: boolean;
}

export const FOOD_INVENTORY_SEED: FoodInventorySeed[] = [
	{ category: 'Dranken', item: 'Water', quantity: 14, lowStock: false },
	{ category: 'Dranken', item: 'Prikwater', quantity: 14, lowStock: false },
	{ category: 'Dranken', item: 'Melk', quantity: 6, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Kersen in blik', quantity: 2, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Bonen in blik', quantity: 3, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Perzik in blik', quantity: 1, lowStock: true },
	{ category: 'Blik/pot groente & fruit', item: 'Ananas in blik', quantity: 1, lowStock: true },
	{ category: 'Blik/pot groente & fruit', item: 'Aardbeienjam', quantity: 2, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Kikkererwten in blik', quantity: 1, lowStock: true },
	{ category: 'Blik/pot groente & fruit', item: 'Sperziebonen in blik', quantity: 4, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Doperwten in blik', quantity: 2, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Mais in blik', quantity: 5, lowStock: false },
	{ category: 'Blik/pot groente & fruit', item: 'Pruimen', quantity: 2, lowStock: false },
	{ category: 'Vis in blik', item: 'Tonijn in blik', quantity: 6, lowStock: false },
	{ category: 'Vis in blik', item: 'Tonijn in blik naturel', quantity: 6, lowStock: false },
	{ category: 'Vis in blik', item: 'Tonijn in blik tomaat', quantity: 9, lowStock: false },
	{ category: 'Vis in blik', item: 'Tonijn in blik groente', quantity: 1, lowStock: true },
	{ category: 'Vis in blik', item: 'Makreel in blik', quantity: 2, lowStock: false },
	{ category: 'Vis in blik', item: 'Sardine in blik', quantity: 1, lowStock: true },
	{ category: 'Sauzen & basis', item: 'Ketjap manis', quantity: 1, lowStock: true },
	{ category: 'Sauzen & basis', item: 'Sojasaus', quantity: 2, lowStock: false },
	{ category: 'Sauzen & basis', item: 'Zonnebloemolie', quantity: 3, lowStock: false },
	{ category: 'Sauzen & basis', item: 'Olijfolie', quantity: 2, lowStock: false },
	{ category: 'Sauzen & basis', item: 'Tomatenpuree', quantity: 7, lowStock: false },
	{ category: 'Sauzen & basis', item: 'Tomaten passata', quantity: 3, lowStock: false },
	{ category: 'Sauzen & basis', item: 'Bechamelsaus', quantity: 3, lowStock: false },
	{ category: 'Bakproducten', item: 'Vanillesuiker (pakjes)', quantity: 27, lowStock: false },
	{ category: 'Bakproducten', item: 'Gist', quantity: 4, lowStock: false },
	{ category: 'Bakproducten', item: 'Bakpoeder', quantity: 3, lowStock: false },
	{ category: 'Bakproducten', item: 'Klopfix', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Aroma', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Kristalsuiker', quantity: 3, lowStock: false },
	{ category: 'Bakproducten', item: 'Bruine basterdsuiker', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Tarwebloem', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Paneermeel', quantity: 2, lowStock: false },
	{ category: 'Bakproducten', item: 'Griesmeel', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Turkse rijst', quantity: 2, lowStock: false },
	{ category: 'Pasta, rijst & granen', item: 'Bolletjes pasta', quantity: 2, lowStock: false },
	{ category: 'Pasta, rijst & granen', item: 'Bulgur', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Vermicelli', quantity: 2, lowStock: false },
	{ category: 'Pasta, rijst & granen', item: 'Couscous', quantity: 4, lowStock: false },
	{ category: 'Pasta, rijst & granen', item: 'Penne', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Tagliatelle', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Fusilli', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Spaghetti', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Havermout', quantity: 1, lowStock: true },
	{ category: 'Pasta, rijst & granen', item: 'Muesli', quantity: 1, lowStock: true },
	{ category: 'Bouillon', item: 'Lamsbouillon', quantity: 0, lowStock: true },
	{ category: 'Bouillon', item: 'Groentebouillon', quantity: 1, lowStock: true },
	{ category: 'Bouillon', item: 'Runderbouillon', quantity: 1, lowStock: true },
	{ category: 'Bouillon', item: 'Visbouillon', quantity: 1, lowStock: true },
	{ category: 'Bouillon', item: 'Kipbouillon (Tavuk)', quantity: 2, lowStock: false },
	{ category: 'Brood & wraps', item: 'Kaiser afvalbrood', quantity: 2, lowStock: false },
	{ category: 'Brood & wraps', item: 'Tortillas', quantity: 1, lowStock: true },
	{ category: 'Brood & wraps', item: 'Hamburgerbrood', quantity: 2, lowStock: false },
	{ category: 'Overig eten', item: 'Nasi trafasi', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Speculoospasta', quantity: 2, lowStock: false },
	{ category: 'Overig eten', item: 'Pindakaas', quantity: 2, lowStock: false },
	{ category: 'Overig eten', item: 'Rozijnen (goud)', quantity: 2, lowStock: false },
	{ category: 'Overig eten', item: 'Pannenkoekenmix', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Pastabladen', quantity: 2, lowStock: false },
	{ category: 'Overig eten', item: 'Sarmabladen', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Kroepoek', quantity: 1, lowStock: true },
	{ category: 'Siropen', item: 'Siroop vanille', quantity: 0, lowStock: true },
	{ category: 'Siropen', item: 'Siroop hazelnoot', quantity: 3, lowStock: false },
	{ category: 'Siropen', item: 'Siroop aardbei', quantity: 1, lowStock: true },
	{ category: 'Siropen', item: 'Sushi azijn', quantity: 0, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Crackers', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Tarwe crackers', quantity: 2, lowStock: false },
	{ category: 'Snacks & ontbijt', item: 'Rijstwafels', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Cornflakes', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Cornflakes kussentjes', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Snickers', quantity: 3, lowStock: false },
	{ category: 'Snacks & ontbijt', item: 'Bueno', quantity: 3, lowStock: false },
	{ category: 'Snacks & ontbijt', item: 'Sensations rood', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Chips sea salt', quantity: 2, lowStock: false },
	{ category: 'Snacks & ontbijt', item: 'Chips paprika', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Chipcookies', quantity: 1, lowStock: true },
	{ category: 'Overig', item: 'Kattenzand', quantity: 1, lowStock: true },
	{ category: 'Overig', item: 'Ijsjes', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Kip', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Kippenbillen', quantity: 3, lowStock: false },
	{ category: 'Diepvries', item: 'Spinazie', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Wokgroente', quantity: 2, lowStock: false },
	{ category: 'Diepvries', item: 'Soepgroente', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Frikandellen', quantity: 22, lowStock: false },
	{ category: 'Diepvries', item: 'Hamburgers', quantity: 14, lowStock: false },
	{ category: 'Diepvries', item: 'Loempias', quantity: 10, lowStock: false },
	{ category: 'Diepvries', item: 'Mini loempias', quantity: 99, lowStock: false },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Simit', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Baguet klein', quantity: 2, lowStock: false },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Rundergehaktvlees', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Borrelvleugels', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Kippenfilet (vers)', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Kalfstagine', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Kalfsbiefstuk extra', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Kalkoen/kip shoarma', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Salade soorten', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Munt (vers)', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Platte peterselie', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Koriander (vers)', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Nectarine', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Fulya cocktailworstjes', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Ankara Kelebek pasta/tahin', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Ulker Laviva wafer', quantity: 1, lowStock: true },
	{ category: 'Overig', item: 'Vochtige doekjes (Sleepy)', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'Schweppes Orange Passion', quantity: 2, lowStock: false },
	{ category: 'Dranken', item: 'Spa water aardbei', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'Pepsi Max limoen', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Meysu kersensap 1L', quantity: 1, lowStock: true },
	{ category: 'Zuivel', item: 'Kookroom 30% (brik 20cl)', quantity: 4, lowStock: false },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Pannenkoeken (kant-en-klaar, 11st)', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'IJskoffie Latte Macchiato', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'IJskoffie Hazelnoot Macchiato', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Rijstpap vanille', quantity: 2, lowStock: false },
	{ category: 'Zuivel', item: 'Kaas geraspt (Paesano)', quantity: 1, lowStock: true },
	{ category: 'Zuivel', item: 'Mozzarella', quantity: 2, lowStock: false },
	{ category: 'Zuivel', item: 'Cheddar (plakjes)', quantity: 1, lowStock: true },
	{ category: 'Zuivel', item: 'Smeltkaas (La Vache Qui Rit)', quantity: 1, lowStock: true },
	{ category: 'Zuivel', item: 'Eieren (12 stuks)', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Citroenen', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Groene olijven met kaasblokjes', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Dip Grieks', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Tapenade groene olijven', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Aardappelen (2,5kg)', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Witte druiven pitloos', quantity: 2, lowStock: false },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Taart (Brésilienne)', quantity: 1, lowStock: true },
	{ category: 'Vers (vlees, brood, kruiden)', item: 'Limoenen', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Roze garnalen gepeld', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Fishsticks', quantity: 1, lowStock: true },
	{ category: 'Diepvries', item: 'Mini pavés (vlees, 4x75g)', quantity: 1, lowStock: true },
	{ category: 'Brood & wraps', item: 'Stokbrood wit (voorgebakken)', quantity: 1, lowStock: true },
	{ category: 'Brood & wraps', item: 'Pitabroodjes (10st)', quantity: 1, lowStock: true },
	{ category: 'Brood & wraps', item: 'Naanbrood look en koriander', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'Cola zero', quantity: 9, lowStock: false },
	{ category: 'Dranken', item: 'Ace Drink', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'Sinaasappelsap', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'Appelsap', quantity: 1, lowStock: true },
	{ category: 'Dranken', item: 'Monster Zero Sugar', quantity: 4, lowStock: false },
	{ category: 'Dranken', item: 'Oploskoffie Gold', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Bruine suiker kandijsmaak', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Puddingpoeder vanille (7x50g)', quantity: 1, lowStock: true },
	{ category: 'Bakproducten', item: 'Maizena (maïszetmeel)', quantity: 1, lowStock: true },
	{ category: 'Sauzen & basis', item: 'Natuurazijn', quantity: 1, lowStock: true },
	{ category: 'Sauzen & basis', item: 'Frituurolie', quantity: 1, lowStock: true },
	{ category: 'Sauzen & basis', item: 'Groene pesto', quantity: 1, lowStock: true },
	{ category: 'Overig eten', item: 'Hazelnootpasta', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Pringles Hot & Spicy', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Pizza crackers', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Popcorn zoet', quantity: 2, lowStock: false },
	{ category: 'Snacks & ontbijt', item: 'Zoute crackertjes', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Chocolade melk hazelnoten', quantity: 1, lowStock: true },
	{ category: 'Snacks & ontbijt', item: 'Chocolade zeevruchten', quantity: 1, lowStock: true },
	{ category: 'Overig', item: 'Wattenschijfjes', quantity: 1, lowStock: true },
	{ category: 'Overig', item: 'Kattensnoep zalm (sticks)', quantity: 1, lowStock: true },
	{ category: 'Overig', item: 'Vochtig toiletpapier (kids)', quantity: 1, lowStock: true }
];

/** One-time seed from the household's voorraad.xlsx "Boodschappenlijst" sheet. */
export interface ShoppingListSeed {
	name: string;
	note: string;
	purchased: boolean;
}

export const SHOPPING_LIST_SEED: ShoppingListSeed[] = [
	{ name: 'Lamsbouillon', note: 'Op uit voorraad', purchased: false },
	{ name: 'Siroop vanille', note: 'Op uit voorraad', purchased: false },
	{ name: 'Sushi azijn', note: 'Op uit voorraad', purchased: false },
	{ name: 'Boter', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Yoghurt', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Suiker (fijne kristalsuiker voor koffie/thee)', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Thee', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Zout', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Peper', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Afwasmiddel', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Wc-papier', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Vuilniszakken', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Tandpasta', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Keukenrol', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false },
	{ name: 'Aluminiumfolie / plastic folie', note: 'Basisbehoefte, ontbreekt in voorraad', purchased: false }
];
